### PR TITLE
Fixed bug in sys clock init, also reported by glory

### PR DESCRIPTION
**Pull request by IsaacDynamo**
Discussion in discord 
https://discord.com/channels/805578807477534750/805580165140447263/896020358996566056

### CODE REVIEW

**Review by dexter93 — CHANGES_REQUESTED** [review]
Per the docs, we should probably keep this one for consistent clock switching.  Just make sure to correct the typo like this
```	//;;;;;;;;; Need for SN32F260 Begin
	if (SystemCoreClock > =24000000)
	{	
		SN_FLASH->LPCTRL = 0x5AFA0005;
	}
	else	//SystemCoreClock < 24000000
	{
		SN_FLASH->LPCTRL = 0x5AFA0000;
	}
	//;;;;;;;;; Need for SN32F260 End
```

Please consider this https://github.com/SonixQMK/ChibiOS-Contrib/pull/25 too

**Comment by IsaacDynamo** [comment]
Per what docs is update of SN_FLASH->LPCTRL in SystemCoreClockUpdate() needed? SystemInit() already configure SN_FLASH->LPCTRL.

Imho SystemCoreClockUpdate() should only update SystemCoreClock. This would be consistent with SystemCoreClockUpdate() from other vendors, stm32, rp2040, nrf52 etc. 

Furthermore I don't really see a usecase for FlashClockUpdate() and SlowModeSwitch() yet.

**Comment by dexter93** [comment]
SlowModeSwitch() is a 248b thing. FlashClockUpdate() can become handy if/when we do clock switching for power profiling in different power states. It's fine on init sure, but if we change clocks we need to be sure flash behaves.

**Comment by IsaacDynamo** [comment]
But wouldn't the SN_FLASH->LPCTRL update via FlashClockUpdate() possibly be to late? 

FlashClockUpdate() looks at SystemCoreClock, which is set in SystemCoreClockUpdate() based on the current AHBPRE. So the system might already be running at a high freq, before SN_FLASH->LPCTRL is updated.

As far as I understand any clock update code must pre-emptively setup SN_FLASH->LPCTRL, before clock switch is done. This is not possible with FlashClockUpdate().

**Comment by IsaacDynamo** [comment]
Actually a 48MHz to 12MHz clock switch would be fine with FlashClockUpdate().
Only 12MHz to 48MHz (or 24MHz) would be an issue

**Comment by dexter93** [comment]
As discussed in discord, merging this one and will do a followup PR for FlashClockUpdate()

**Pull request merged**
