### PR TITLE
Fixed usb transmitting being unreliable

### PR DESCRIPTION
**Pull request by susch19**
* by always handling the ack and nak flags, even when other flags are present

I know that this version is different from the original implementation of the driver by sonix, but at least for me, it seems to be the most stable one. During stress testing send and receive I got 500 packages for each direction and a total loss of 0.00019% packages from a total of 7,232,000. 14mio if you count both directions. And this loss is either rec or send, as I just checked if I got an answer for each package, not if it arrived at the keyboard and if I got an answer.
Also, with this version via worked as it should (Creating macros, changing keys, reconnecting after restarting keyboard). With all other version via would break the UI update, as soon as I create a new macro.

So in the end, I don't know why it fixes it (maybe because ack and nak need to be always handeled?) and why the original sonix driver did different things, but atleast i'm happy, as it seems to be working now as it should.

### CODE REVIEW

**Comment by susch19** [comment]
Currently running another stress test for the OpenRGB side, but it goes pretty well and afaik openrgb doesn't even send 500 packages per second, even on 60fps. Even when sending an every info per key, it would only be 4bit per key * 110 (Something like that) will only be 440 bytes. 440 / 60 (4 byte header just in case) = 8 Packages.  8x60 = 420 packages, so even with the via response per package and an unoptimized protocol (which openrgb doesn't have) it still has some headroom.
But i will still let it run for some time and will make it ready to review, as soon as the tests are finished

**Comment by susch19** [comment]
So after 2 full days of use and testing openrgb (continuously) and via (occasionally) this seems to be stable. 
I detected no weird behavior or missed key strokes or anything like that, so I would be comfortable to declare it as "stable for now"

**Comment by Jpe230** [comment]
After nuking and restoring my dev. environment, it comes to my attention that neither does OPENRGB and VIA works using your branch. I had to to revert the code deleted in #45 inside the "handleNAK" function for it to work. 

Im using Intel CPUs with WSL, MSYS and MacOS to compile and test.

**Comment by dexter93** [comment]
Hi guys. I think I found it 
https://github.com/ChibiOS/ChibiOS-Contrib/pull/371

tested on  [`ChibiOS/ChibiOS-Contrib`](https://github.com/ChibiOS/ChibiOS-Contrib/tree/chibios-21.11.x), seems to fix transmission issues

**Pull request closed without merging**
